// Generated by CoffeeScript 1.8.0
'use strict';
var $, cfg, gulp;

cfg = require('../config.json');

gulp = require('gulp');

$ = require('gulp-load-plugins')();

gulp.task('watch', function() {
  gulp.watch('*.coffee', {
    cwd: 'dev'
  }, ['coffeescript']);
});
